version: '3.7'

services:
  ETNAIR-postgres:
    image: postgres:latest
    container_name: Database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootRoot
      POSTGRES_DB: ETNAIR
    expose:
      - '5432'
      - '8080'
    ports:
      - '5432:5432'
      - '8080:8080'
    networks:
      - backend
    volumes:
      - './data/postgresql:/var/lib/postgresql/data'
      - './sql/:/home/app/'
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr", "-p", "5432"]
    
networks:
  backend:
    driver: bridge

volumes:
  postgresql_data:
    driver: local