version: '3'
services:
  db:
    image: postgres:latest
    container_name: db_etnair
    volumes: 
    - db_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: etnair_db
  api:
    depends_on:
      - db
    image: node:latest
    container_name: api_etnair
    ports: 
      - "3000:3000"
    restart: always
    environment:
      API_DB_HOST: db:3000
      API_DB_USER: user
      API_DB_PASSWORD: password
      API_DB_NAME: enair_db
volumes:
  db_data:
