# version: '3.9'
services:
  db:
    image: postgres:latest
    volumes: 
    - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: etnair_db
    networks:
      - etnair_network
      - db_network
  api:
    depends_on:
      - db
    image: node:latest
    ports: 
      - "3000:3000"
    restart: always
    environment:
      API_DB_HOST: db
      API_DB_USER: user
      API_DB_PASSWORD: password
      API_DB_NAME: enair_db
    networks:
      - etnair_network
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "start"]
volumes:
  db_data:
networks:
  etnair_network:
    driver: bridge
  db_network:
    driver: bridge