openapi: 3.1.0
info:
  title: ETNAir
  description: Rental site
  version: 0.0.1

servers:
- url: http://localhost:3000
  description: Serveur de développement

tags:
  - name: user
    description: user related route
  - name: ads
    description: ads related route
paths:
  /utilisateurs:
    get:
      tags:
        - user
      description: All users
      responses:
        200:
          description: Return all the users of the database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    post:
      tags:
        - user
      description: create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
      201:
        description: User created
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
  /utilisateurs/{id}:
    parameters:
        - name: id
          in: path
          description: User id
          required: true
          schema:
            type: integer
    get:
      tags:
        - user
      description: a user
      responses:
        200:
          description: Return a user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: Return a not found error
    put:
      tags:
        - user
      description: Update user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
      200:
        description: User updated
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
    delete:
      tags:
        - user
      description: a user
      responses:
        204:
          description: User deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: Return a not found error
  /annonces:
    get:
      tags:
        - ads
      description: All ad
      responses:
        200:
          description: Return all the ads of the database
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Advert'
    post:
      tags:
        - ads
      description: create advert
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Advert"
      responses:
      201:
        description: Advert created
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Advert"
  /annonces/{id}:
    parameters:
        - name: id
          in: path
          description: Ad id
          required: true
          schema:
            type: integer
    get:
      tags:
        - ads
      description: an ad
      responses:
        200:
          description: Return an ad
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Advert'
        404:
          description: Return a not found error
    put:
      tags:
        - ads
      description: Update ad
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Advert"
      responses:
      200:
        description: Advert updated
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Advert"
    delete:
      tags:
        - ads
      description: an advert
      responses:
        204:
          description: Advert deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Advert'
        404:
          description: Return a not found error


components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        age:
          type: number
      additionalProperties: false
      required:
        - id
        - name
        - age
    Advert:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
        description:
          type: string
      additionalProperties: false
      required:
        - id
        - name
        - age
