swagger: "2.0"
info:
  title: ETNAir
  description: Rental site
  version: 0.0.1

servers:
  - url: http://localhost:3000
    description: Serveur de développement

tags:
  - name: user
    description: user related route
  - name: rentals
    description: rentals related route

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

paths:
  /users:
    get:
      security:
        - Bearer: []
      tags:
        - user
      description: All users
      responses:
        200:
          description: Return all the users of the database
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        401:
          description: "Unauthorized access: token required !"
  /auth/register:
    post:
      tags:
        - user
      description: create user
      parameters:
        - in: body
          name: body
          description: User object for registration
          required: true
          schema:
            $ref: "#/components/schemas/User"
      responses:
        201:
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: "Bad request: Invalid parameters !"
        409:
          description: "Conflict: Duplicate phone number or email !"
  /auth/login:
    post:
      tags:
        - user
      description: create user
      parameters:
        - in: body
          name: body
          description: User object for registration
          required: true
          schema:
            $ref: "#/components/schemas/Login"
      responses:
        200:
          description: User connected
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Login"
        401:
            description: Wrong password
        404:
            description: Wrong email
  /user:
    get:
      security:
        - Bearer: []
      tags:
        - user
      description: a user
      responses:
        200:
          description: Return a user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        401:
          description: "Unauthorized access: token required !"
    put:
      security:
        - Bearer: []
      tags:
        - user
      description: Update user
      parameters:
        - in: body
          name: body
          description: User object for registration
          required: true
          schema:
            $ref: "#/components/schemas/User"
      responses:
      200:
        description: User updated
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
    delete:
      security:
        - Bearer: []
      tags:
        - user
      description: a user
      responses:
        204:
          description: User deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        401:
          description: "Unauthorized access: token required !"
  /rentals:
    get:
      tags:
        - ads
      description: All ad
      responses:
        200:
          description: Return all the ads of the database
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Advert"
    post:
      tags:
        - ads
      description: create advert
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Advert"
      responses:
      201:
        description: Advert created
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Advert"
  /rentals/{id}:
    parameters:
      - name: id
        in: path
        description: Ad id
        required: true
        schema:
          type: integer
    get:
      tags:
        - ads
      description: an ad
      responses:
        200:
          description: Return an ad
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Advert"
        404:
          description: Return a not found error
    put:
      tags:
        - ads
      description: Update ad
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Advert"
      responses:
      200:
        description: Advert updated
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Advert"
    delete:
      tags:
        - ads
      description: an advert
      responses:
        204:
          description: Advert deleted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Advert"
        404:
          description: Return a not found error

components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        password:
          type: string
        about_me:
          type: string
        phone_number:
          type: string
      additionalProperties: false
      required:
        - email
        - name
        - password
        - phone_number
    Login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      additionalProperties: false
      required:
        - email
        - password
    Advert:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
        description:
          type: string
      additionalProperties: false
      required:
        - id
        - name
        - age
