openapi: 3.1.0
info:
  title: ETNAir
  description: Location pas cher
  version: 0.0.1

servers:
- url: http://localhost:3000
  description: Serveur de développement

tags:
  - name: pokemon
    description: api de pokemons
